### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by WarlaxZ**
Added a healthcheck :)

### CODE REVIEW

**Comment by nvllsvm** [comment]
Can wget be used instead of curl? It's already included in the base Alpine image.

**Comment by WarlaxZ** [comment]
It was causing issues when I tried using wget, kept complaining it couldn't find web, even when I manually tried with the external address



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by nvllsvm** [comment]
Changed to wget. Using wget /web/index.html worked, but only after the initial startup wizard. Went with /swagger instead.

**Comment by nvllsvm** [comment]
Thanks!

**Pull request merged**
